# postgres:latest
services:
  postgres:
    image: postgres:latest
    container_name: postgres
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: course
      POSTGRES_PASSWORD: changeme
      POSTGRES_DB: movies
    volumes:
      - ./data:/var/lib/postgresql/data